apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: etcd-node-exporter
    app.kubernetes.io/vendor: kubesphere
  name: etcd-node-exporter
  namespace: kubesphere-monitoring-system
spec:
  endpoints:
  - interval: 1m
    port: metrics
    metricRelabelings:
    - action: keep
      regex: node_cpu_.+|node_memory_Mem.+_bytes|node_memory_SReclaimable_bytes|node_memory_Cached_bytes|node_memory_Buffers_bytes|node_network_(.+_bytes_total|up)|node_network_.+_errs_total|node_nf_conntrack_entries.*|node_disk_.+_completed_total|node_disk_.+_bytes_total|node_filesystem_files|node_filesystem_files_free|node_filesystem_avail_bytes|node_filesystem_size_bytes|node_filesystem_free_bytes|node_filesystem_readonly|node_load.+|node_timex_offset_seconds
      sourceLabels:
      - __name__
    # relabelings:
    # - action: labeldrop
    #   regex: (service|endpoint)
    # - action: replace
    #   regex: (.*)
    #   replacement: $1
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: etcd-node-exporter
