---
# docker image repo define
argocd_dexidp_image: "dexidp/dex:v2.27.0"
argocd_argocd_image: "argoproj/argocd:v2.0.4"
argocd_redis_image: "redis:6.2.4-alpine"

argocd_http_node_port: 30280
argocd_https_node_port: 30281

enable_grafana: false
enable_etcd_monitoring: true

grafana_tag: 7.4.3
grafana_http_node_port: 30380
extra_dashboard: |-
  {
      "__inputs": [],
      "__requires": [],
      "annotations": {
          "list": []
      },
      "editable": false,
      "gnetId": null,
      "graphTooltip": 0,
      "hideControls": false,
      "id": null,
      "links": [],
      "panels": [
          {
              "content": "The SLO (service level objective) and other metrics displayed on this dashboard are for informational purposes only.",
              "datasource": null,
              "description": "The SLO (service level objective) and other metrics displayed on this dashboard are for informational purposes only.",
              "gridPos": {
                  "h": 2,
                  "w": 24,
                  "x": 0,
                  "y": 0
              },
              "id": 2,
              "mode": "markdown",
              "span": 12,
              "title": "Notice",
              "type": "text"
          }
      ],
      "refresh": "10s",
      "rows": [
          {
              "collapse": false,
              "collapsed": false,
              "panels": [
                  {
                      "cacheTimeout": null,
                      "colorBackground": false,
                      "colorValue": false,
                      "colors": [
                          "#299c46",
                          "rgba(237, 129, 40, 0.89)",
                          "#d44a3a"
                      ],
                      "datasource": "$datasource",
                      "decimals": 3,
                      "description": "How many percent of requests (both read and write) in 30 days have been answered successfully and fast enough?",
                      "format": "percentunit",
                      "gauge": {
                          "maxValue": 100,
                          "minValue": 0,
                          "show": false,
                          "thresholdLabels": false,
                          "thresholdMarkers": true
                      },
                      "gridPos": {},
                      "id": 3,
                      "interval": null,
                      "links": [],
                      "mappingType": 1,
                      "mappingTypes": [
                          {
                              "name": "value to text",
                              "value": 1
                          },
                          {
                              "name": "range to text",
                              "value": 2
                          }
                      ],
                      "maxDataPoints": 100,
                      "nullPointMode": "connected",
                      "nullText": null,
                      "postfix": "",
                      "postfixFontSize": "50%",
                      "prefix": "",
                      "prefixFontSize": "50%",
                      "rangeMaps": [
                          {
                              "from": "null",
                              "text": "N/A",
                              "to": "null"
                          }
                      ],
                      "span": 4,
                      "sparkline": {
                          "fillColor": "rgba(31, 118, 189, 0.18)",
                          "full": false,
                          "lineColor": "rgb(31, 120, 193)",
                          "show": false
                      },
                      "tableColumn": "",
                      "targets": [
                          {
                              "expr": "apiserver_request:availability30d{verb=\"all\", cluster=\"$cluster\"}",
                              "format": "time_series",
                              "intervalFactor": 2,
                              "legendFormat": "",
                              "refId": "A"
                          }
                      ],
                      "thresholds": "",
                      "title": "Availability (30d) > 99.000%",
                      "tooltip": {
                          "shared": false
                      },
                      "type": "singlestat",
                      "valueFontSize": "80%",
                      "valueMaps": [
                          {
                              "op": "=",
                              "text": "N/A",
                              "value": "null"
                          }
                      ],
                      "valueName": "avg"
                  },
                  {
                      "aliasColors": {},
                      "bars": false,
                      "dashLength": 10,
                      "dashes": false,
                      "datasource": "$datasource",
                      "decimals": 3,
                      "description": "How much error budget is left looking at our 0.990% availability gurantees?",
                      "fill": 10,
                      "gridPos": {},
                      "id": 4,
                      "legend": {
                          "alignAsTable": false,
                          "avg": false,
                          "current": false,
                          "max": false,
                          "min": false,
                          "rightSide": false,
                          "show": true,
                          "sideWidth": null,
                          "total": false,
                          "values": false
                      },
                      "lines": true,
                      "linewidth": 1,
                      "links": [],
                      "nullPointMode": "null",
                      "percentage": false,
                      "pointradius": 5,
                      "points": false,
                      "renderer": "flot",
                      "repeat": null,
                      "seriesOverrides": [],
                      "spaceLength": 10,
                      "span": 8,
                      "stack": false,
                      "steppedLine": false,
                      "targets": [
                          {
                              "expr": "100 * (apiserver_request:availability30d{verb=\"all\", cluster=\"$cluster\"} - 0.990000)",
                              "format": "time_series",
                              "intervalFactor": 2,
                              "legendFormat": "errorbudget",
                              "refId": "A"
                          }
                      ],
                      "thresholds": [],
                      "timeFrom": null,
                      "timeShift": null,
                      "title": "ErrorBudget (30d) > 99.000%",
                      "tooltip": {
                          "shared": false,
                          "sort": 0,
                          "value_type": "individual"
                      },
                      "type": "graph",
                      "xaxis": {
                          "buckets": null,
                          "mode": "time",
                          "name": null,
                          "show": true,
                          "values": []
                      },
                      "yaxes": [
                          {
                              "decimals": 3,
                              "format": "percentunit",
                              "label": null,
                              "logBase": 1,
                              "max": null,
                              "min": null,
                              "show": true
                          },
                          {
                              "decimals": 3,
                              "format": "percentunit",
                              "label": null,
                              "logBase": 1,
                              "max": null,
                              "min": null,
                              "show": true
                          }
                      ]
                  }
              ],
              "repeat": null,
              "repeatIteration": null,
              "repeatRowId": null,
              "showTitle": false,
              "title": "Dashboard Row",
              "titleSize": "h6",
              "type": "row"
          }
      ],
      "schemaVersion": 14,
      "style": "dark",
      "tags": [
          "kubernetes-mixin"
      ],
      "templating": {
          "list": [
              {
                  "current": {
                      "text": "default",
                      "value": "default"
                  },
                  "hide": 0,
                  "label": null,
                  "name": "datasource",
                  "options": [],
                  "query": "prometheus",
                  "refresh": 1,
                  "regex": "",
                  "type": "datasource"
              },
              {
                  "allValue": null,
                  "current": {},
                  "datasource": "$datasource",
                  "hide": 2,
                  "includeAll": false,
                  "label": "cluster",
                  "multi": false,
                  "name": "cluster",
                  "options": [],
                  "query": "label_values(apiserver_request_total, cluster)",
                  "refresh": 2,
                  "regex": "",
                  "sort": 1,
                  "tagValuesQuery": "",
                  "tags": [],
                  "tagsQuery": "",
                  "type": "query",
                  "useTags": false
              },
              {
                  "allValue": null,
                  "current": {},
                  "datasource": "$datasource",
                  "hide": 0,
                  "includeAll": true,
                  "label": null,
                  "multi": false,
                  "name": "instance",
                  "options": [],
                  "query": "label_values(apiserver_request_total{job=\"apiserver\", cluster=\"$cluster\"}, instance)",
                  "refresh": 2,
                  "regex": "",
                  "sort": 1,
                  "tagValuesQuery": "",
                  "tags": [],
                  "tagsQuery": "",
                  "type": "query",
                  "useTags": false
              }
          ]
      },
      "time": {
          "from": "now-1h",
          "to": "now"
      },
      "timepicker": {
          "refresh_intervals": [
              "5s",
              "10s",
              "30s",
              "1m",
              "5m",
              "15m",
              "30m",
              "1h",
              "2h",
              "1d"
          ],
          "time_options": [
              "5m",
              "15m",
              "1h",
              "6h",
              "12h",
              "24h",
              "2d",
              "7d",
              "30d"
          ]
      },
      "timezone": "UTC",
      "title": "Extra / Extra Dashboard",
      "uid": "09ec8aa1e996d6ffcd6817bbaff4db1b",
      "version": 0
  }
